version: '3'

services:
  demos:
    depends_on:
      - nginx
    image: localhost:32000/alpine-miniconda3-pyviz:latest
    volumes:
      - ~/Documents/betest:/mnt/betest:ro
    #reminder: fix for internal use only and add REST API for external

    ports:
      - 5006:5006
    deploy:
      replicas: 3
    restart: always
    command: bokeh serve /mnt/betest/testapp.py --allow-websocket-origin=demo.ryptco.com:5006

  frontend:
    depends_on:
      - nginx
    image: localhost:32000/fetest:latest
    links:
      - demos
    volumes:
      - /home/alkire/Documents/fetest:/app:ro
    restart: always

  nginx:  
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/error.log:/etc/nginx/error_log.log
      # - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
    restart: always