version: '3'

services:
  frontend:
    depends_on:
      - nginx
    image: fetest:latest
    restart: always

  nginx:  
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/error.log:/etc/nginx/error_log.log
      # - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
    restart: always





